stages:
    - deploy

.deploy: &deploy_template
    tags:
        - shared-runner
    stage: deploy
    image: composer:1.9
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval "$(ssh-agent -s)"
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - chmod 0700 ~/.ssh
        - echo "$SSH_SERVER_HOSTKEYS" >> ~/.ssh/known_hosts
        
Deploy to Stage:
  <<: *deploy_template
  only:
    - main
  script:
    - scp Unity/docs/index.md "$HOSTSERVER":httpdocs/source/unity/
    - scp -r Unity/docs/images/* "$HOSTSERVER":httpdocs/source/unity/docs/images
    - ssh "$HOSTSERVER" "cd httpdocs/ && make html"